/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jvmemorama;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * Integrantes:
 * Mendoza Hernández Dylan Michel
 * Mohedano Torres Efraín
 */
public class jfrmMemorama extends javax.swing.JFrame {
    clsMemorama objMemorama;
    URL urlImagen;
    int segundosTrans;
    Timer tmrPartida = new Timer(1000, new ActionListener (){
        public void actionPerformed(ActionEvent e){
            mostrarTimer();
        }
    });
    

    /**
     * Creates new form jfrmMemorama
     */
    public jfrmMemorama() {
        initComponents();
        objMemorama = new clsMemorama();
        mostrarComponentes();
        segundosTrans = 0;
        asignarImagenes();
    }
    public void mostrarImagen(JLabel imagenLogo, String urlImg){
        urlImagen = this.getClass().getResource(urlImg);
        ImageIcon imgL = new ImageIcon(urlImagen);
        Icon imagen = new ImageIcon(imgL.getImage().getScaledInstance(imagenLogo.getWidth(), imagenLogo.getHeight(), Image.SCALE_DEFAULT));
        imagenLogo.setIcon(imagen);
        this.repaint();
    }
    public void mostrarTarjetas(JButton imagenLogo, String urlImag) {
        urlImagen = this.getClass().getResource(urlImag);
        ImageIcon imgL = new ImageIcon(urlImagen);
        Icon imagen = new ImageIcon(imgL.getImage().getScaledInstance(imagenLogo.getWidth(), imagenLogo.getHeight(), Image.SCALE_DEFAULT));
        imagenLogo.setIcon(imagen);
        this.repaint();
    }
    
    public void mostrarTimer(){
        if (objMemorama.getIniciar()) {
            objMemorama.getBotones().get(0).setEnabled(false);
            if (objMemorama.getContSegundos() > 0 & objMemorama.getContSegundos() < 3) {
                objMemorama.setContSegundos(objMemorama.getContSegundos()+1);
                if (objMemorama.getContSegundos() == 3) {
                    for (int i = 0; i < 2; i++) {
                        mostrarTarjetas(objMemorama.getTarjetas().get(objMemorama.getTarjetasVolteadas()[i]), "/imagenes/portada.jpg");
                    }
                    objMemorama.setContSegundos(0);
                }
            }
            if (segundosTrans==0) {
                asignarImagenes();
            }
            objMemorama.getEtiquetas().get(4).setText("Pares encontrados: " + objMemorama.getNumParesCorrectos());
            objMemorama.getEtiquetas().get(5).setText("Pares erróneos: " + objMemorama.getNumParesFallos());
            objMemorama.getEtiquetas().get(3).setText("Tiempo restante: " + (60 - segundosTrans));
            if (segundosTrans >= 60 || objMemorama.getNumParesCorrectos() == objMemorama.getImagenesMemorama().length) {
                objMemorama.setInciar(false);
                segundosTrans = 0;
                objMemorama.setContSegundos(0);
                if (objMemorama.getNumParesCorrectos() == objMemorama.getImagenesMemorama().length) {
                    JOptionPane.showMessageDialog(null, "¡Felicidades ganaste, acertaste todos los pares!");
                }else{
                    JOptionPane.showMessageDialog(null, "Lo siento perdiste, tu tiempo se ha agotado");
                }
                objMemorama.getBotones().get(0).setEnabled(true);
                
            }else{
                segundosTrans++;
            }
        }
    }
    public void mostrarComponentes(){
        objMemorama.crearPanel(this);
        objMemorama.crearEtiquetas();
        objMemorama.crearBotones(this, tmrPartida);
        objMemorama.crearTarjetas(this, tmrPartida);
        mostrarImagen(objMemorama.getEtiquetas().get(0), "/imagenes/logo.jpg");
    }
    public void asignarImagenes(){
        for (int i = 0; i < objMemorama.getTarjetas().size(); i++){
            mostrarTarjetas(objMemorama.getTarjetas().get(i), "/imagenes/portada.jpg");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 430));
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmMemorama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmMemorama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmMemorama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmMemorama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmMemorama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
